//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZEdit.rc
//
#define ID_IGNORE                       3
#define IDBROWSE                        3
#define ID_DELETE                       3
#define ID_FILE_CLOSEALL                4
#define ID_FILE_SAVEAS                  6
#define ID_FILE_SAVEALL                 7
#define ID_FILE_PAGESETUP               8
#define ID_HELP_ABOUT                   10
#define ID_FILE_EXIT                    11
#define ID_EDIT_SELECTALL               27
#define ID_EDIT_FINDPREV                28
#define ID_EDIT_FINDNEXT                29
#define ID_OPTIONS_FONT                 40
#define ID_TOOLS_SHOWCODES              41
#define ID_OPTIONS_GOTO                 42
#define ID_OPTIONS_WRAP                 43
#define ID_OPTIONS_TAB                  44
#define IDC_HEADCODES                   101
#define IDC_FOOTCODES                   102
#define IDC_FILENAME                    103
#define IDR_MAINMENU                    105
#define IDR_ZEDIT                       108
#define IDC_SCROLL_MIDDLE               113
#define IDD_ABOUT                       116
#define IDC_SCROLL_UP                   117
#define IDD_TABS                        118
#define IDD_GOTOLINE                    119
#define IDC_SCROLL_DOWN                 120
#define IDD_FIND                        123
#define IDB_SCROLL                      125
#define IDD_PAGESETUP                   128
#define IDB_TOOLBAR                     133
#define IDC_LINK                        134
#define IDD_PRINT                       139
#define IDD_ENTERCHAR                   140
#define IDD_VIEWCODES                   141
#define IDI_ZEDIT                       162
#define IDD_NEWFILE                     171
#define IDD_SORT                        172
#define IDD_SPELL                       173
#define IDD_FILEMANAGER                 175
#define IDD_SYNTAXCOLOR                 180
#define IDB_TOOLBAR_256                 181
#define IDB_TOOLBAR_DISABLED            182
#define IDD_OPTIONS                     183
#define IDD_FINDINFILES                 184
#define IDB_COLUMN_LINE                 185
#define IDD_COLUMNMARKER                186
#define IDR_CONTEXT                     187
#define ID_Menu                         190
#define ID_TOOLS_INSERTCHAR             192
#define IDC_MOVEFILE                    196
#define ID_TABS_OPENFOLDER              199
#define ID_FILE_FILE1                   300
#define ID_FILE_FILE2                   301
#define ID_FILE_FILE3                   302
#define ID_FILE_FILE4                   303
#define ID_FILE_FILE5                   304
#define ID_FILE_FILE6                   305
#define ID_FILE_FILE7                   306
#define ID_FILE_FILE8                   307
#define ID_FILE_FILE9                   308
#define ID_FILE_FILE10                  309
#define ID_FILE_FILE11                  310
#define ID_FILE_FILE12                  311
#define ID_FILE_FILE13                  312
#define ID_FILE_FILE14                  313
#define ID_FILE_FILE15                  314
#define ID_FILE_FILE16                  315
#define ID_FILE_FILE17                  316
#define ID_FILE_FILE18                  317
#define ID_FILE_FILE19                  318
#define ID_FILE_FILE20                  319
#define ID_PAGE_FILENAME                400
#define ID_PAGE_PAGE                    401
#define ID_PAGE_TIME                    402
#define ID_PAGE_DATE                    403
#define ID_PAGE_LEFT                    404
#define ID_PAGE_CENTER                  405
#define ID_PAGE_RIGHT                   406
#define ID_PAGE_PATHNAME                407
#define ID_SEARCH_TABCHARACTER          421
#define ID_SEARCH_CARETCHARACTER        422
#define ID_SEARCH_UNICODECODE           423
#define ID_SEARCH_ASCIICODE             426
#define ID_FILE_NEWTYPE                 427
#define ID_TOOLS_SORT                   428
#define ID_TOOLS_SPELL                  429
#define ID_WINDOW_MANAGER               430
#define ID_WINDOW_PREV                  431
#define ID_WINDOW_NEXT                  432
#define ID_WINDOW_SPLITVERT             433
#define ID_WINDOW_SPLITHORIZ            434
#define ID_FILEMANAGER_ACTIVATE         444
#define ID_FILEMANAGER_SAVE             445
#define ID_FILEMANAGER_CLOSE            446
#define ID_FILEMANAGER_CLOSEMANAGER     447
#define ID_FILEMANAGER_FIND             448
#define ID_FILE_PROPERTIES              449
#define ID_TOOLS_SYNTAX                 450
#define ID_TOOLS_FINDINFILES            451
#define ID_TOOLS_CHANGECASE             453
#define ID_EDIT_OPEN                    454
#define ID_TABS_CLOSE                   455
#define ID_TABS_SAVE                    457
#define ID_TABS_SAVEAS                  458
#define ID_TABS_SWITCHTO                460
#define ID_TABS_PROPERTIES              462
#define ID_COLUMNS_DELETE               463
#define ID_COLUMNS_COLOR                464
#define ID_COLUMNS_EDIT                 465
#define ID_TABS_CLOSEEXCEPT             466
#define ID_TABS_CLOSEALL                467
#define ID_TABS_SAVEALL                 468
#define ID_OPTIONS_COLUMNS              469
#define ID_EDIT_BINARY                  470
#define ID_TOOLS_FIXLINE                471
#define ID_FINDINFILES_COPYTOCLIPBOARD  472
#define ID_FILEDROP_CANCEL              473
#define ID_SEARCH_PARAGRAPH             474
#define ID_OPTIONS_DEFAULTMODE          475
#define ID_DEFAULTMODE_ANSI             476
#define ID_DEFAULTMODE_UNICODE          477
#define ID_DEFAULTMODE_UNICODE478       478
#define ID_OPTIONS_DEFAULTENC_ANSI      482
#define ID_OPTIONS_DEFAULTENC_UTF8      483
#define ID_OPTIONS_DEFAULTENC_UTF16     484
#define IDC_EDIT                        1010
#define IDC_POSSIBLE                    1012
#define IDC_COMBO_FIND                  1013
#define IDC_COMBO_REPLACE               1014
#define IDC_COMBO_FILTER                1015
#define IDC_WHOLEWORD                   1016
#define IDC_MATCHCASE                   1017
#define IDC_FINDNEXT                    1018
#define IDC_REPLACE                     1019
#define IDC_COMBO_DIRECTION             1020
#define IDC_REPLACEALL                  1021
#define IDC_STATIC_REPLACE              1032
#define IDC_STATIC_SEARCH               1033
#define IDC_STATIC3                     1034
#define IDC_HEADER                      1037
#define IDC_FOOTER                      1038
#define IDC_LEFT                        1040
#define IDC_RIGHT                       1041
#define IDD_PROPERTIES                  1041
#define IDC_TOP                         1042
#define IDC_BOTTOM                      1043
#define IDD_STATISTICS                  1043
#define IDC_HEADER_MARGIN               1044
#define IDD_FINDRESULTS                 1044
#define IDC_FOOTER_MARGIN               1045
#define IDD_FIXLINES                    1045
#define IDD_CHANGECASE                  1046
#define IDC_PRINTFILE                   1062
#define IDC_PRINTPAGE                   1063
#define IDC_VALUES                      1067
#define IDC_LISTTYPE                    1071
#define IDC_CASE                        1076
#define ID_CHANGE                       1076
#define IDC_DESCENDING                  1077
#define ID_SUGGEST                      1078
#define IDC_LISTVIEW                    1083
#define IDC_TABPOS                      1088
#define IDC_CHARS                       1089
#define IDC_LOADTIME                    1090
#define IDC_MEMORY                      1091
#define IDC_REPLACEFILES                1093
#define IDC_BLOCK_START                 1094
#define IDC_BLOCK_STOP                  1095
#define IDC_PARA                        1097
#define IDC_GROUP                       1098
#define IDC_KEYWORD                     1099
#define IDC_GROUP_NEW                   1100
#define IDC_GROUP_DEL                   1101
#define IDC_GROUP_REN                   1102
#define IDC_BLOCK_COLOR                 1103
#define IDC_GROUP_COLOR                 1104
#define IDC_SCHEMES                     1105
#define IDC_EXT                         1106
#define IDC_DEFAULT_COLOR               1107
#define IDC_NEWZEDIT                    1108
#define IDC_SUBFOLDERS                  1111
#define IDC_FOLDER                      1117
#define IDC_STATIC_HEAD                 1118
#define IDC_STATIC_FOOT                 1119
#define IDC_STATIC_MATCH                1120
#define IDC_STATIC_REPLACE_MENU         1121
#define IDC_STATIC_FIND_MENU            1122
#define ID_ADD                          1125
#define IDC_COLUMN                      1127
#define IDC_CRLF                        1128
#define IDC_CR                          1129
#define IDC_LF                          1130
#define IDC_FRAME                       1130
#define IDC_CRLF2                       1131
#define IDC_TOGGLE                      1131
#define IDC_LF2                         1132
#define IDC_TITLE                       1132
#define IDC_LOWER                       1133
#define IDC_UPPER                       1134
#define IDC_SENTENCE                    1135
#define IDC_NOTE                        1136
#define ID_OPENAS_ANSI                  2000
#define ID_OPENAS_UTF8                  2001
#define ID_OPENAS_UTF16                 2002
#define ID_OPENAS_DEFAULT               2004
#define ID_OPENAS_FILENAME              2005
#define ID_OPENAS_PATHNAME              2006
#define IDC_FILEICON                    13057
#define IDC_MSDOS                       13058
#define IDC_FILETYPE                    13059
#define IDC_FILESIZE                    13064
#define IDC_LOCATION                    13065
#define IDC_CREATED                     13072
#define IDC_MODIFIED                    13073
#define IDC_ACCESSED                    13074
#define IDC_READONLY                    13075
#define IDC_HIDDEN                      13076
#define IDC_ARCHIVE                     13077
#define IDC_SYSTEM                      13078
#define IDC_PARAS                       13079
#define IDC_GETLINE                     32668

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         485
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
